name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            set -e
            cd /root/opt/advini-advocacia-next
            git pull origin main
            
            # Create environment file
            cat > .env.local << EOL
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
            EOL
            
            # Build and deploy with Docker
            docker build -t advini-advocacia:latest .
            docker stop advini-advocacia || true
            docker rm advini-advocacia || true
            docker run -d --restart=always --name advini-advocacia --env-file .env.local -p 3000:3000 advini-advocacia:latest
            
            # Clean up unused Docker resources
            docker system prune -af --volumes